# Generated by Django 5.2.5 on 2025-09-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_image', models.ImageField(upload_to='apps/')),
                ('main_image', models.ImageField(upload_to='apps/')),
                ('mini_icon', models.ImageField(upload_to='apps/')),
                ('download_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
