# Generated by Django 5.2.5 on 2025-09-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='main_image2',
            field=models.ImageField(default=1, upload_to='apps/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='mini_icon2',
            field=models.ImageField(default=1, upload_to='apps/'),
            preserve_default=False,
        ),
    ]
