# Generated by Django 5.2.5 on 2025-09-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_app_main_image2_app_mini_icon2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='main_image',
            new_name='main_image1',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='mini_icon',
            new_name='mini_icon1',
        ),
    ]
