# Generated by Django 5.2.5 on 2025-09-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_main_image_app_main_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='apps/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='main_image1',
            field=models.ImageField(blank=True, null=True, upload_to='apps/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='main_image2',
            field=models.ImageField(blank=True, null=True, upload_to='apps/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='mini_icon1',
            field=models.ImageField(blank=True, null=True, upload_to='apps/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='mini_icon2',
            field=models.ImageField(blank=True, null=True, upload_to='apps/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
