# Generated by Django 5.2.5 on 2025-09-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_app_tagline_alter_app_logo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='download_file',
            field=models.ImageField(blank=True, null=True, upload_to='apps/'),
        ),
    ]
