# Generated by Django 5.2.5 on 2025-09-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_app_download_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='apps/files/'),
        ),
    ]
