# Generated by Django 5.2.5 on 2025-09-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_app_download_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
