# Generated by Django 5.2.5 on 2025-09-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_app_download_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='download_link',
            new_name='download_link1',
        ),
        migrations.AddField(
            model_name='app',
            name='download_link2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
