# Generated by Django 5.2.5 on 2025-09-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_download_link_app_download_link1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='download_file',
            new_name='download_file1',
        ),
        migrations.AddField(
            model_name='app',
            name='download_file2',
            field=models.FileField(blank=True, null=True, upload_to='apps/files/'),
        ),
    ]
