# Generated by Django 5.2.5 on 2025-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_download_file_app_download_file1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iPhone / iPad')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
