# Generated by Django 5.2.5 on 2025-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_app_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='download_file1',
            new_name='download_file',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='download_link1',
            new_name='download_link',
        ),
        migrations.RemoveField(
            model_name='app',
            name='download_file2',
        ),
        migrations.RemoveField(
            model_name='app',
            name='download_link2',
        ),
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'ios')], max_length=20),
        ),
    ]
