# Generated by Django 5.2.5 on 2025-09-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_download_file1_app_download_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='main_image1',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='mini_icon1',
            new_name='mini_icon',
        ),
        migrations.RemoveField(
            model_name='app',
            name='main_image2',
        ),
        migrations.RemoveField(
            model_name='app',
            name='mini_icon2',
        ),
    ]
