# Generated by Django 5.2.5 on 2025-09-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_main_image1_app_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='mini_icon',
        ),
    ]
