# Generated by Django 5.2.5 on 2025-09-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_app_mini_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='main_image1',
            field=models.ImageField(blank=True, null=True, upload_to='apps/'),
        ),
        migrations.AddField(
            model_name='app',
            name='main_image2',
            field=models.ImageField(blank=True, null=True, upload_to='apps/'),
        ),
    ]
