# Generated by Django 5.2.5 on 2025-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_app_main_image1_app_main_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
