# Generated by Django 5.2.5 on 2025-09-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_app_download_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
