# Generated by Django 5.2.5 on 2025-09-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(blank=True, default='dcb7ceb9', max_length=8, unique=True)),
                ('admin_name', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
