# Generated by Django 4.2 on 2025-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='admin_id',
            field=models.CharField(blank=True, default='c5b72d12', max_length=8, unique=True),
        ),
    ]
