# Generated by Django 4.2 on 2025-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadadmin', '0002_alter_adminuser_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='admin_id',
            field=models.CharField(blank=True, default='93a6575e', max_length=8, unique=True),
        ),
    ]
